global:
  resolve_timeout: 5m

route:
  receiver: 'email_notifications'
  group_by: ['alertname', 'method', 'endpoint']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email_notifications'
    email_configs:
      - to: 'your-email@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'smtp_user'
        auth_password: 'smtp_password'
        auth_identity: 'smtp_user'
        require_tls: true